# Generated by Django 6.1 on 2026-08-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('geocode_source', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['lat', 'lng'], name='station_lat_lng_idx'), models.Index(fields=['city', 'state'], name='station_city_state_idx')],
            },
        ),
    ]
